# Generated by Django 5.2.7 on 2025-11-05 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
        ('tags', '0002_alter_tag_name_alter_tag_usage_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Голоса'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at', 'is_active'], name='questions_q_created_e621b1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['votes', 'is_active'], name='questions_q_votes_bab3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', 'created_at'], name='questions_q_author__a83c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'author'], name='questions_q_is_acti_3113bc_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvote',
            index=models.Index(fields=['user', 'question'], name='questions_q_user_id_436917_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvote',
            index=models.Index(fields=['question', 'value'], name='questions_q_questio_27de00_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvote',
            index=models.Index(fields=['user', 'created_at'], name='questions_q_user_id_3c10a5_idx'),
        ),
    ]
