# Generated by Django 5.2.7 on 2025-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('votes', models.IntegerField(default=0, verbose_name='Голоса')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-is_correct', '-votes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')], verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата голоса')),
            ],
            options={
                'verbose_name': 'Голос за ответ',
                'verbose_name_plural': 'Голоса за ответы',
            },
        ),
    ]
