# Generated by Django 5.2.7 on 2025-11-05 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0003_alter_question_content_alter_question_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct', '-votes'], name='answers_ans_questio_9b1f58_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author', 'created_at'], name='answers_ans_author__c0ec7b_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_active', 'created_at'], name='answers_ans_is_acti_3223ef_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['votes'], name='answers_ans_votes_d817ef_idx'),
        ),
        migrations.AddIndex(
            model_name='answervote',
            index=models.Index(fields=['user', 'answer'], name='answers_ans_user_id_3810f0_idx'),
        ),
        migrations.AddIndex(
            model_name='answervote',
            index=models.Index(fields=['answer', 'value'], name='answers_ans_answer__2a4af6_idx'),
        ),
    ]
