# Generated by Django 5.2.7 on 2025-11-10 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_alter_answer_author'),
        ('questions', '0005_alter_question_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='answers_ans_questio_9b1f58_idx',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct', '-votes', 'created_at'], name='answers_ans_questio_e7322f_idx'),
        ),
    ]
