# Generated by Django 5.2.7 on 2025-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, verbose_name='Описание тега')),
                ('color', models.CharField(default='#1864BD', max_length=7, verbose_name='Цвет тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
