# Generated by Django 5.2.7 on 2025-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Количество использований'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-usage_count', 'name'], name='tags_tag_usage_c_0af0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx'),
        ),
    ]
