# Generated by Django 5.2.7 on 2025-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_name_alter_tag_usage_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Название тега'),
        ),
    ]
